#!/usr/bin/env python3
"""Render a reviewed Debian host policy. No host settings are changed."""
import argparse
import ipaddress
import json
from pathlib import Path
import re


class PolicyError(ValueError):
    pass


def load(path):
    def unique(pairs):
        result = {}
        for key, value in pairs:
            if key in result:
                raise PolicyError('Duplicate configuration field: ' + key)
            result[key] = value
        return result
    config = json.loads(Path(path).read_text(), object_pairs_hook=unique)
    expected = {'external_interfaces', 'admin_networks', 'admin_users', 'ssh_port',
                'mqtt_networks', 'dhcp4', 'dhcp6'}
    if not isinstance(config, dict) or set(config) != expected:
        raise PolicyError('Supply exactly the fields in host.example.json.')
    for key, pattern in [('external_interfaces', r'[A-Za-z0-9][A-Za-z0-9_.:-]{0,14}'),
                         ('admin_users', r'[a-z_][a-z0-9_-]{0,31}')]:
        values = config[key]
        if (not isinstance(values, list) or not values or len(values) > 16
                or any(not isinstance(v, str) or not re.fullmatch(pattern, v) for v in values)
                or len(values) != len(set(values))):
            raise PolicyError('Invalid or repeated values in ' + key)
    if 'root' in config['admin_users'] or 'lo' in config['external_interfaces']:
        raise PolicyError('Use non-root administrators and non-loopback external interfaces.')
    for key in ('admin_networks', 'mqtt_networks'):
        values = config[key]
        if not isinstance(values, list) or not values or len(values) > 128:
            raise PolicyError('Supply explicit source networks for ' + key)
        networks = []
        for value in values:
            if not isinstance(value, str):
                raise PolicyError('Networks must be CIDR strings.')
            network = ipaddress.ip_network(value, strict=True)
            if network.is_multicast or network.is_loopback or network.is_unspecified:
                raise PolicyError('Invalid source network: ' + value)
            if key == 'admin_networks' and network.prefixlen == 0:
                raise PolicyError('SSH administration must not be open to the whole Internet.')
            networks.append(str(network))
        if len(networks) != len(set(networks)):
            raise PolicyError('Repeated source network in ' + key)
        config[key] = networks
    if type(config['ssh_port']) is not int or not 1 <= config['ssh_port'] <= 65535:
        raise PolicyError('ssh_port must be 1..65535.')
    if config['ssh_port'] in (80, 443, 8883):
        raise PolicyError('SSH must not share an application port.')
    if any(type(config[key]) is not bool for key in ('dhcp4', 'dhcp6')):
        raise PolicyError('DHCP settings must be explicit booleans.')
    return config


def source_rules(networks, suffix):
    rules = []
    for version, family in [(4, 'ip'), (6, 'ip6')]:
        values = [v for v in networks if ipaddress.ip_network(v).version == version]
        if values:
            rules.append(f'        iifname $external {family} saddr {{ {", ".join(values)} }} {suffix}')
    return '\n'.join(rules)


def firewall(config):
    interfaces = ', '.join(json.dumps(v) for v in config['external_interfaces'])
    ssh = source_rules(config['admin_networks'], f'tcp dport {config["ssh_port"]} counter accept')
    mqtt_input = source_rules(config['mqtt_networks'], 'tcp dport 8883 counter accept')
    mqtt_forward = source_rules(config['mqtt_networks'], 'meta l4proto tcp ct status dnat ct original proto-dst 8883 counter accept')
    dhcp = ''
    if config['dhcp4']:
        dhcp += '        iifname $external udp sport 67 udp dport 68 accept\n'
    if config['dhcp6']:
        dhcp += '        iifname $external ip6 saddr fe80::/10 udp sport 547 udp dport 546 accept\n'
    # add is idempotent; delete+recreate happens inside one nft transaction.
    # Never flush the global ruleset: Docker and fail2ban own other tables.
    return f'''# Generated by DanuBaaS security/debian/render.py
# Only this table is replaced; Docker and fail2ban rules are preserved.
define external = {{ {interfaces} }}
add table inet danubaas_host
delete table inet danubaas_host
table inet danubaas_host {{
    chain input {{
        type filter hook input priority -10; policy drop;
        iifname "lo" accept
        ct state invalid drop
        ct state established,related accept
        # ICMP supports diagnostics, PMTU and IPv6 neighbour discovery/SLAAC.
        meta l4proto {{ icmp, ipv6-icmp }} accept
{dhcp}{ssh}
        iifname $external tcp dport {{ 80, 443 }} counter accept
{mqtt_input}
        limit rate 5/second burst 10 packets log prefix "danubaas-input-drop "
        counter drop
    }}
    chain forward {{
        type filter hook forward priority -10; policy drop;
        ct state invalid drop
        ct state established,related accept
        # Default Docker bridge names; later Docker chains still enforce isolation.
        iifname "docker0" accept
        iifname "br-*" accept
        # Original published ports, after Docker's PREROUTING DNAT.
        iifname $external meta l4proto tcp ct status dnat ct original proto-dst {{ 80, 443 }} counter accept
{mqtt_forward}
        # Block new external traffic to every other published/direct-routed port.
        iifname $external limit rate 5/second burst 10 packets log prefix "danubaas-forward-drop "
        counter drop
        # Docker retains responsibility for bridge isolation and container egress.
    }}
}}
'''


def artifacts(config):
    return {
        'firewall.nft': firewall(config),
        '00-danubaas.conf': f'''# Place in /etc/ssh/sshd_config.d/; verify effective settings before reload.
Port {config['ssh_port']}
AllowUsers {' '.join(config['admin_users'])}
PermitRootLogin no
PubkeyAuthentication yes
AuthenticationMethods publickey
PasswordAuthentication no
KbdInteractiveAuthentication no
PermitEmptyPasswords no
UsePAM yes
MaxAuthTries 3
LoginGraceTime 30
X11Forwarding no
AllowAgentForwarding no
PermitTunnel no
GatewayPorts no
AllowTcpForwarding local
PermitOpen 127.0.0.1:1880 localhost:1880
LogLevel VERBOSE
''',
        'danubaas.local': f'''# /etc/fail2ban/jail.d/danubaas.local; host SSH only, not container web logs.
[sshd]
enabled = true
backend = systemd
port = {config['ssh_port']}
banaction = nftables-multiport
findtime = 10m
maxretry = 5
bantime = 1h
ignoreip = 127.0.0.1/8 ::1 {' '.join(config['admin_networks'])}
''',
        '60-danubaas.conf': '''# /etc/sysctl.d/60-danubaas.conf
# Do not change forwarding, IPv6 enablement or rp_filter: Docker/VPNs need review.
fs.protected_hardlinks = 1
fs.protected_symlinks = 1
fs.protected_fifos = 2
fs.protected_regular = 2
kernel.kptr_restrict = 2
kernel.dmesg_restrict = 1
kernel.yama.ptrace_scope = 1
net.ipv4.conf.all.accept_redirects = 0
net.ipv4.conf.default.accept_redirects = 0
net.ipv4.conf.all.secure_redirects = 0
net.ipv4.conf.default.secure_redirects = 0
net.ipv4.conf.all.send_redirects = 0
net.ipv4.conf.default.send_redirects = 0
net.ipv6.conf.all.accept_redirects = 0
net.ipv6.conf.default.accept_redirects = 0
net.ipv4.conf.all.accept_source_route = 0
net.ipv4.conf.default.accept_source_route = 0
net.ipv6.conf.all.accept_source_route = 0
net.ipv6.conf.default.accept_source_route = 0
net.ipv4.tcp_syncookies = 1
''',
        '52danubaas-unattended-upgrades': '''// /etc/apt/apt.conf.d/52danubaas-unattended-upgrades
// Explicit security origins; keep Debian package-managed defaults in place.
#clear Unattended-Upgrade::Origins-Pattern;
Unattended-Upgrade::Origins-Pattern {
    "origin=Debian,codename=${distro_codename},label=Debian-Security";
    "origin=Debian,codename=${distro_codename}-security,label=Debian-Security";
};
Unattended-Upgrade::Automatic-Reboot "false";
APT::Periodic::Update-Package-Lists "1";
APT::Periodic::Unattended-Upgrade "1";
''',
        'danubaas-firewall.service': '''[Unit]
Description=DanuBaaS host and Docker ingress firewall
DefaultDependencies=no
After=local-fs.target
Before=network-pre.target docker.service shutdown.target
Wants=network-pre.target
Conflicts=shutdown.target

[Service]
Type=oneshot
RemainAfterExit=yes
ExecStart=/usr/sbin/nft -f /etc/danubaas-security/firewall.nft
ExecReload=/usr/sbin/nft -f /etc/danubaas-security/firewall.nft
# Stopping this service deliberately leaves rules active.

[Install]
WantedBy=multi-user.target
''',
    }


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--config', required=True, type=Path)
    parser.add_argument('--output', required=True, type=Path)
    args = parser.parse_args()
    try:
        files = artifacts(load(args.config))
        args.output.mkdir(mode=0o700, parents=True, exist_ok=False)
        for name, content in files.items():
            (args.output / name).write_text(content)
        print(f'Rendered {len(files)} files in {args.output}. Review them before installation.')
    except (OSError, ValueError) as error:
        parser.exit(1, str(error) + '\n')


if __name__ == '__main__':
    main()
